"""Edit Admin

Revision ID: e94d167d2b38
Revises: 46de636713d6
Create Date: 2025-10-30 07:03:22.502218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e94d167d2b38'
down_revision: Union[str, Sequence[str], None] = '46de636713d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('admins', 'last_name')
    op.drop_column('admins', 'first_name')
    op.drop_column('admins', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('middle_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admins', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('admins', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('admins', 'password')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
